name: aether-vault

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'   # Public HTTP Port
      - '81:81'   # Admin Web UI Port
      - '443:443' # Public HTTPS Port
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  aethervault:
    image: filebrowser/filebrowser:latest
    container_name: aethervault-docker
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ./files:/srv
      - ./database/filebrowser.db:/database/filebrowser.db
      - ./.env:/config/.env
    restart: always
