name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Power Cleanup
        # This force-kills everything and the network to prevent "Already Exists" errors
        run: |
          docker rm -f nginx-proxy-tf aethervault-terraform cadvisor prometheus grafana loki promtail 2>/dev/null || true
          docker network rm aether-network-tf 2>/dev/null || true
          sudo fuser -k 80/tcp 8080/tcp 3000/tcp 9090/tcp 3100/tcp || true
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # We pass the project_root variable directly to avoid EOF errors
        run: terraform apply -auto-approve -var="project_root=/home/anumoymajhi/project/project-ssh-cloud/aether-vault"
